# Generated by Django 4.2.3 on 2024-01-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeproduct',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
