# Generated by Django 4.2.3 on 2024-01-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipeproduct_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeproduct',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
